# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20180722_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(blank=True, default='abc', max_length=15, unique=True),
        ),
    ]
